# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: snapcraft
email: anthony.dillon@canonical.com
description: Introducing snaps and commands to install and remove them on Ubuntu 16.04 LTS.
keywords: snappy, Ubuntu Core, Ubuntu 16.04 LTS, snaps, apps, debs, snap, docker, coreos, atomic, snapcraft, snapd
baseurl: ""
asset_path: https://assets.ubuntu.com/v1/
navigation:
- text: Home
  url: /
- text: Create
  url: /create/
exclude: [
  'LICENCE',
  'README.md',
  'Gulpfile.js',
  'package.json',
  'node_modules',
  'translate-html',
  'import-docs.sh',
  'update-docs-layout.py',
  'po-html'
]
permalink: /:title

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# only build incrementally
incremental: true
